"""One command for a REAL local dry-run environment (A-38). Also reachable as `mbos devdb up --lane-d`.

    .venv/bin/python -I tools/bootstrap_dev.py [--skip-install] [--ui-pin PIN]

Starts the project-local pgserver cluster, provisions lane D (Agent 04) with split logins through 04's own `provision()`
(worker `mbos_dbos`, owner `mbos_operator_ui`), installs lanes 02/03/05 from their PUSHED heads (tools/sync_lanes.py), extracts lane 06's
planner and Operator UI, copies lane E's policy, and writes `var/dev.env` (worker; every MBOS_* variable) and `var/owner.env` (owner login only,
mode 0600). Idempotent. Everything is DRY-RUN; nothing here contacts anyone.
"""

from __future__ import annotations

import argparse
import importlib
import io
import os
import shutil
import subprocess
import sys
import tarfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(Path(__file__).resolve().parent))
STATE_REF, GOV_REF, UI_REF = "origin/research/agent-04-state", "origin/research/agent-05-governance", "origin/research/agent-06-communications"
APP_DB = "mbos_dev"


def _archive(ref: str, dest: Path, *paths: str) -> str:
    """Extract `paths` of a pushed head into dest (replacing it). Read-only; never touches another lane's worktree."""
    tar = subprocess.run(["git", "archive", ref, *paths], cwd=ROOT, capture_output=True, check=True).stdout
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)
    tarfile.open(fileobj=io.BytesIO(tar)).extractall(dest, filter="data")
    return subprocess.run(["git", "rev-parse", "--short", ref], cwd=ROOT, capture_output=True, text=True, check=True).stdout.strip()


def _provision(admin_dsn: str, state_src: Path):
    sys.path.insert(0, str(state_src))
    try:
        return importlib.import_module("mbos_state.provision").provision(admin_dsn, app_db=APP_DB, sys_db=f"{APP_DB}_sys")
    finally:
        sys.path.remove(str(state_src))


def _write(path: Path, lines: list[str], mode: int) -> None:
    path.write_text("\n".join(lines) + "\n")
    path.chmod(mode)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--skip-install", action="store_true", help="do not (re)install lane packages from pushed heads")
    ap.add_argument("--ui-pin", default="dev-pin", help="PIN printed in the Operator UI command (default: dev-pin)")
    ap.add_argument("--var-dir", default=str(ROOT / "var"), help="where dev.env, owner.env, lanes/, policy/, raw/ go (default: ./var, gitignored)")
    a = ap.parse_args(argv)
    var = Path(a.var_dir).resolve()
    lanes_dir = var / "lanes"

    import pgserver  # dev dependency

    subprocess.run(["git", "fetch", "-q", "origin"], cwd=ROOT, check=True)
    var.mkdir(parents=True, exist_ok=True)

    if not a.skip_install:
        import sync_lanes

        if sync_lanes.main():
            print("lane install failed", file=sys.stderr)
            return 1

    state_sha = _archive(STATE_REF, lanes_dir / "state", "state")
    ui_sha = _archive(UI_REF, lanes_dir / "agent-06", "operator_ui", "comms_spec")
    gov_sha = _archive(GOV_REF, lanes_dir / "policy-src", "policy")
    policy_dir = var / "policy"
    if policy_dir.exists():
        shutil.rmtree(policy_dir)
    shutil.copytree(lanes_dir / "policy-src" / "policy", policy_dir)

    devdb = Path(os.environ.get("MBOS_DEVDB_DIR", ROOT / ".pgdata")).resolve()
    server = pgserver.get_server(devdb, cleanup_mode=None)  # keep running after this process exits
    prov = _provision(server.get_uri(), lanes_dir / "state" / "state")
    raw = var / "raw"
    raw.mkdir(exist_ok=True)
    (var / "comps_inbox").mkdir(exist_ok=True)

    py_path = os.pathsep.join([str(lanes_dir / "agent-06"), os.environ.get("PYTHONPATH", "")]).rstrip(os.pathsep)
    _write(var / "dev.env", [
        "# generated by tools/bootstrap_dev.py: WORKER login only (no approver). The owner login is in var/owner.env.",
        f"export MBOS_DATABASE_URL='{prov.app_url}'",
        f"export MBOS_SYSTEM_DATABASE_URL='{prov.sys_url}'",
        "export MBOS_STATE_BACKEND='lane_d'",
        "export MBOS_GATEWAY_MODE='lane_e'",
        "export MBOS_SCORER='engine'",
        f"export MBOS_RAW_DIR='{raw}'",
        f"export MBOS_COMPS_STORE='{var / 'discovery' / 'comps.json'}'",   # written by `mbos-discover` comps collection
        f"export MBOS_COMPS_INBOX='{var / 'comps_inbox'}'",               # comps Michael entered (ManualCompsAdapter JSON files)
        f"export MBOS_POLICY_PATH='{policy_dir / 'policy.v1.json'}'",
        f"export MBOS_EGRESS_FILE='{ROOT / 'var' / 'egress_policy.json'}'",
        f"export MBOS_LITELLM_FILE='{ROOT / 'var' / 'litellm_keys.json'}'",
        f"export PYTHONPATH='{py_path}'",
    ], 0o644)
    _write(var / "owner.env", [
        "# generated by tools/bootstrap_dev.py: the OWNER login (approver). Source it ONLY in the shell where Michael decides; never for `mbos worker`.",
        f"export MBOS_OWNER_DATABASE_URL='{prov.owner_app_url}'",
    ], 0o600)

    py = ".venv/bin/python"
    print(f"lane D {state_sha} provisioned ({APP_DB}); lane E policy {gov_sha}; lane F {ui_sha}; migrations applied this run: {len(prov.migrations_applied)}")
    print(f"""
Next (each in the repo root):
  1. worker shell:   source var/dev.env && .venv/bin/mbos worker --fixture fixtures/sources/illustrative.json
                     (prints the REAL/STAND-IN report; only `sources` should be STAND-IN)
  2. a card:         source var/dev.env && .venv/bin/mbos queue          # then: mbos card ITEM_ID
  3. operator UI:    source var/dev.env && source var/owner.env && MBOS_OPERATOR_PIN={a.ui_pin} {py} -u -m operator_ui serve --port 8765
  4. decide:         source var/dev.env && source var/owner.env && .venv/bin/mbos decide AREQ_ID YES --seen HASHPREFIX
  stop:              .venv/bin/mbos devdb down""")
    return 0


if __name__ == "__main__":
    sys.exit(main())
